vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    quizz_image:
      uri_prefix: "%quizz_image%"
      upload_destination: "%kernel.project_dir%/public%quizz_image%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
